# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    # The most common configuration options are documented and commented below.
    # For a complete reference, please see the online documentation at
    # https://docs.vagrantup.com.

    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://atlas.hashicorp.com/search.
    config.vm.box = "bento/ubuntu-18.04"

    config.vm.network "forwarded_port", guest: 8000, host: 8000 # API Client
    config.vm.network "forwarded_port", guest: 80, host: 8080 # Nginx Client
    config.vm.network "forwarded_port", guest: 7000, host: 8001
    config.vm.network "forwarded_port", guest: 15672, host: 3000 # RabbitMQ Client
    config.vm.synced_folder "../", "/vagrant"
    config.vm.synced_folder "salt", "/srv/salt"
    config.vm.synced_folder "pillar", "/srv/pillar"

    # This is required because we are using gitfs as the backend
    # for the salt provisioner defined below.
    config.vm.provision "shell", path: "bootstrap.sh"

    config.vm.provision :salt do |salt|
        salt.run_highstate = true
        salt.masterless = true
        salt.minion_config = "minion"
    end

end
